import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F7F7F2' },
  flex: { flex: 1 },
  header: { padding: 20, paddingBottom: 8 },
  title: { fontSize: 24, fontWeight: '700', color: '#1C1C1C' },
  subtitle: { fontSize: 14, color: '#4E4E4E', marginTop: 4 },
  container: { padding: 20, paddingTop: 12, paddingBottom: 24, gap: 12 },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 18,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  dayCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E7ECEF',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  sectionTitle: { fontSize: 18, fontWeight: '700', marginBottom: 12, color: '#1E1E1E' },
  subsectionTitle: { fontSize: 15, fontWeight: '600', marginBottom: 8, color: '#2A2A2A' },
  helper: { fontSize: 13, color: '#6B6B6B', marginBottom: 12 },
  field: { marginBottom: 12 },
  label: { fontSize: 13, color: '#2D2D2D', marginBottom: 6 },
  input: {
    borderWidth: 1,
    borderColor: '#D6D1C8',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    backgroundColor: '#FAF9F6',
  },
  inputDisabled: { backgroundColor: '#EEEAE2', color: '#8C8C8C' },
  otherRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  otherInlineInput: { flex: 1, paddingVertical: 8 },
  inputText: { fontSize: 14, color: '#2D2D2D' },
  inputPlaceholder: { color: '#8C8C8C' },
  dateModalCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    gap: 12,
  },
  fileRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  fileButton: {
    backgroundColor: '#1F6E4E',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  fileButtonText: { color: '#FFFFFF', fontWeight: '600', fontSize: 12 },
  fileRemoveButton: {
    backgroundColor: '#6E6E6E',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  fileRemoveButtonText: { color: '#FFFFFF', fontWeight: '600', fontSize: 12 },
  fileName: { flex: 1, fontSize: 12, color: '#4E4E4E' },
  optionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  optionChip: {
    borderWidth: 1,
    borderColor: '#B8B0A4',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    marginBottom: 6,
  },
  optionChipSelected: { backgroundColor: '#1F6E4E', borderColor: '#1F6E4E' },
  optionText: { fontSize: 13, color: '#3B3B3B' },
  optionTextSelected: { color: '#FFFFFF' },
  buttonRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, marginTop: 12 },
  button: {
    flex: 1,
    backgroundColor: '#1F6E4E',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  secondaryButton: { backgroundColor: '#A7742E' },
  buttonDisabled: { opacity: 0.5 },
  buttonText: { color: '#FFFFFF', fontWeight: '600' },
  group: { marginBottom: 12 },
  radioRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#8C8C8C',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  radioOuterSelected: { borderColor: '#1F6E4E' },
  radioInner: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#1F6E4E' },
  radioLabel: { fontSize: 14, color: '#2C2C2C' },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#8C8C8C',
    marginRight: 10,
    backgroundColor: '#FFFFFF',
  },
  checkboxChecked: { backgroundColor: '#1F6E4E', borderColor: '#1F6E4E' },
  checkboxLabel: { fontSize: 14, color: '#2C2C2C' },
  summaryCard: {
    borderWidth: 1,
    borderColor: '#E2DDD4',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    backgroundColor: '#FBFAF7',
  },
  summaryCardPressed: { opacity: 0.85 },
  summarySectionTitle: { textAlign: 'center' },
  summaryTitle: { fontSize: 15, fontWeight: '600', marginBottom: 8, color: '#1F1F1F', textAlign: 'center' },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  summaryLabel: { flex: 1, fontSize: 13, color: '#444444', textAlign: 'left' },
  summaryValue: { flex: 1, fontSize: 13, color: '#444444', textAlign: 'right', fontWeight: '700' },
  summaryExportButton: { marginTop: 10 },
  logbookRow: {
    borderWidth: 1,
    borderColor: '#E6EAEE',
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    backgroundColor: '#FFFFFF',
  },
  logbookRowActive: {
    borderColor: '#3D8528',
    backgroundColor: '#EEF7EA',
  },
  logbookDate: { fontSize: 15, fontWeight: '700', color: '#1F2937' },
  logbookMeta: { fontSize: 12, fontWeight: '700', color: '#6B7280', marginTop: 2 },
  settingsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F7',
  },
  settingsLabel: { fontSize: 14, fontWeight: '700', color: '#374151' },
  settingsValue: { fontSize: 14, fontWeight: '800', color: '#111827' },
  tabBar: {
    flexDirection: 'row',
    paddingTop: 8,
    paddingBottom: 10,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
  },
  tabButton: {
    flex: 1,
    height: 44,
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonActive: {
    backgroundColor: '#F4F8F5',
  },
  tabLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6B7280',
  },
  tabLabelActive: {
    color: '#1E5128',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
});
